### ISSUE TITLE
Fix.Apply with two diagnostics throws NRE

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Roslyn.Asserts#60]
```
   at Gu.Roslyn.Asserts.Fix.<GetActionsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gu.Roslyn.Asserts.Fix.<ApplyAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gu.Roslyn.Asserts.Fix.Apply(Solution solution, CodeFixProvider codeFix, IReadOnlyList`1 diagnostics, String fixTitle)
   at Gu.Localization.Analyzers.Tests.GULOC03UseResourceTests.CodeFix.MoveToResource(String value, String key) in C:\Git\Gu.Localization\Gu.Localization.Analyzers.Tests\GULOC03UseResourceTests\CodeFix.cs:line 45
```

**Comment by JohanLarsson** [comment]
```cs
        [Test]
        public void SingleClassTwoErrorCorrectFix()
        {
            var code = @"
namespace RoslynSandbox
{
    class Foo
    {
        private readonly int _value1;
        private readonly int _value2;
    }
}";

            var fixedCode = @"
namespace RoslynSandbox
{
    class Foo
    {
        private readonly int value1;
        private readonly int value2;
    }
}";
            var analyzer = new FieldNameMustNotBeginWithUnderscore();
            var cSharpCompilationOptions = CodeFactory.DefaultCompilationOptions(analyzer);
            var metadataReferences = new[] { MetadataReference.CreateFromFile(typeof(int).Assembly.Location) };
            var sln = CodeFactory.CreateSolution(code, cSharpCompilationOptions, metadataReferences);
            var diagnostics = Analyze.GetDiagnostics(sln, analyzer);
            var fixedSln = Fix.Apply(sln, new DontUseUnderscoreCodeFixProvider(), diagnostics);
            CodeAssert.AreEqual(fixedCode, fixedSln.Projects.Single().Documents.Single());
        }
```
