### ISSUE TITLE
Testing FixAll codefix results in a NullReferenceException

### ISSUE THREAD

**Issue by dnperfors** [GuOrg/Gu.Roslyn.Asserts#81]
I am trying to test a codefix that supports FixAll using the following implementation:
```
public override FixAllProvider GetFixAllProvider()
{
    return WellKnownFixAllProviders.BatchFixer;
}
```
Testing this code with `AnalyzerAssert.FixAll`, results in an `NullReferenceException` somewhere inside the BatchFixer.

**Comment by JohanLarsson** [comment]
Hmm, this sounds vaguely familiar. I'm pretty sure I've seen this and the NRE was inside Roslyn. Can you post a stack trace? Also we need a repro to fix this in a good way. Thanks for reporting!

**Comment by JohanLarsson** [comment]
What version of `Microsoft.CodeAnalysis` are you using? You can try changing to referencing `2.3.1` and see if that resolves the problem. I understand that it is not a fix for the issue, I mean it as a debugging step.

**Comment by dnperfors** [comment]
I am using `2.6.0` of `Microsoft.CodeAnalysis` (since I need IOperation support for some analyzer), but switching to `2.3.1` doesn't change anything.

I get the following stacktrace, so yes it seems to be inside Roslyn, but perhaps some setup is not done?:
```
Result StackTrace:	
at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryAddDocumentMergeChangesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFinalDocumentTextAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetDocumentIdToFinalTextAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryMergeFixesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryGetMergedFixAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gu.Roslyn.Asserts.Fix.<ApplyAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gu.Roslyn.Asserts.Fix.<ApplyAllFixableScopeByScopeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gu.Roslyn.Asserts.AnalyzerAssert.FixAllByScope(DiagnosticAnalyzer analyzer, CodeFixProvider codeFix, Solution sln, IReadOnlyList`1 fixedCode, String fixTitle, AllowCompilationErrors allowCompilationErrors, FixAllScope scope)
   at Gu.Roslyn.Asserts.AnalyzerAssert.FixAll(DiagnosticAnalyzer analyzer, CodeFixProvider codeFix, DiagnosticsAndSources diagnosticsAndSources, IReadOnlyList`1 fixedCode, IEnumerable`1 suppressedDiagnostics, IReadOnlyList`1 metadataReferences, String fixTitle, AllowCompilationErrors allowCompilationErrors)
   at Gu.Roslyn.Asserts.AnalyzerAssert.FixAll[TAnalyzer,TCodeFix](IReadOnlyList`1 codeWithErrorsIndicated, String fixedCode, String fixTitle, AllowCompilationErrors allowCompilationErrors)
   at -- snip --
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

I tried to create a simple reproduction using the existing tests and codefixes in this repo, but I didn't succeed yet... I will continue working on it.

**Comment by JohanLarsson** [comment]
https://github.com/dotnet/roslyn/issues/22710

**Comment by dnperfors** [comment]
It seems to be fixed with a later version of Roslyn, when I change the version of Roslyn to `2.7.0` or higher I don't get the error...

**Comment by dnperfors** [comment]
Note that I only have to change the rolsyn version of the test, not of my actual analyzer and codefix, not ideal, but probably better than a hack as workaround.

**Comment by JohanLarsson** [comment]
We can add a hack in the test library to compensate for the roslyn bug. Does not have to be pretty, a nice thing to do for other users.
