### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Roslyn.Asserts#92]
When using `Microsoft.CodeAnalysis.Common 2.9`

```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Threading.Tasks.ValueTask`1.get_IsCompleted()
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildDeclarationCompilationFromScratchAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Gu.Roslyn.Asserts.Analyze.GetDiagnostics(DiagnosticAnalyzer analyzer, Solution solution)
   at Gu.Roslyn.Asserts.AnalyzerAssert.CodeFix(DiagnosticAnalyzer analyzer, CodeFixProvider fix, DiagnosticsAndSources diagnosticsAndSources, String fixedCode, IEnumerable`1 suppressedDiagnostics, IEnumerable`1 metadataReferences, String fixTitle, AllowCompilationErrors allowCompilationErrors)
   at Gu.Roslyn.Asserts.AnalyzerAssert.CodeFix[TAnalyzer,TCodeFix](String codeWithErrorsIndicated, String fixedCode, String fixTitle, AllowCompilationErrors allowCompilationErrors)
   at Gu.Roslyn.Asserts.Tests.WithMetadataReferencesAttribute.AnalyzerAssertTests.CodeFixSingleClassOneErrorCorrectFix()
```

**Comment by JohanLarsson** [comment]
For some reason pinning `nuget System.Runtime.CompilerServices.Unsafe 4.5.1` solves the problem. Not sure why it is needed. From what I can see in the lock file latest version should be fine but no redirects are generated via `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

**Comment by jarzab3** [comment]
Hi @JohanLarsson ,
I have a the same issue with this  assembly `System.Runtime.CompilerServices.Unsafe` with different Version=`4.0.4.1`
When you said pinning `nuget System.Runtime.CompilerServices.Unsafe 4.5.1` what do you mean by this?
Thank you

**Comment by JohanLarsson** [comment]
With pin I meant specifying an exact version of the nuget package. Looks like [this](https://github.com/DotNetAnalyzers/ReflectionAnalyzers/blob/master/paket.dependencies#L7) using paket.

**Comment by ENikS** [comment]
@JohanLarsson @SimonSDA  

So, reading this thread I got confused. Should it be version 4.5.1 or latest >=4.5.2 is fine?

**Comment by JohanLarsson** [comment]
Depends on Roslyn version I think. I've been unpinning with latest. Unpinning as in using latest version of both.

**Comment by kpbaranwal** [comment]
Installing  version 4.5.1 of System.Runtime.CompilerServices.Unsafe worked for me too. I downgraded from 4.5.2 where I was getting the same error.
